### ISSUE TITLE
mkimphttab.create_table() Does not run.

### ISSUE THREAD

**Issue by sean-lockwood** [spacetelescope/reftools#19]
https://github.com/spacetelescope/reftools/blob/efa71b1997f78a7e3da4f44e0461be8412784502/reftools/graphtab.py#L503

This causes errors:  `TypeError: iter() returned non-iterator of type 'dict_values'`

Should it be this instead?:
`for edge in node.edges.values():`

cc: @tonysohn

**Comment by pllim** [comment]
This code was written a while ago and not maintained much. Can you provide the Python version and a standalone code snippet to fully reproduce your problem here? Thanks. cc @sosey

**Comment by sean-lockwood** [comment]
Python 3.7.2
reftools.__version_long__ = '1.7.4-0-g503b8e13'


`from reftools import mkimphttab`
`mkimphttab.create_table('test_stis', 'stis', '*', 'Sep 03 2019 00:00:00', clobber=True, verbose=True)`

I believe the first example listed here also reproduces the error:  https://reftools.readthedocs.io/en/latest/mkimphttab.html

**Comment by pllim** [comment]
According to releases, there is a 1.7.5 tagged already, so your 1.7.4 might be outdated. How did you install it and how long ago?

**Comment by sean-lockwood** [comment]
I reinstalled it yesterday via the Conda channel.  1.7.4 is the only version there.

https://ssb.stsci.edu/astroconda/

**Comment by pllim** [comment]
Okay, that is a separate problem. Anyway, I can reproduce using `master`. I thought Bernie caught the PY2 to PY3 stuff here but maybe not:

https://github.com/spacetelescope/reftools/blob/efa71b1997f78a7e3da4f44e0461be8412784502/reftools/graphtab.py#L153-L158

**Comment by pllim** [comment]
@sean-lockwood , please see if #20 fixes your problem. Thanks!

**Comment by sean-lockwood** [comment]
Was able to build a STIS file.  Thanks!

**Comment by pllim** [comment]
@sean-lockwood , do you want to make sure the values are actually correct before I merge #20?

**Comment by sean-lockwood** [comment]
We will need to do some acceptance testing on the file over the next few weeks anyway, so it probably shouldn't hold up the merge.

**Comment by pllim** [comment]
Okay. Then, please open new issues if you find something else. Thanks for reporting this!
