### ISSUE TITLE
MNT: Replace PySynphot with synphot_refactor

### ISSUE THREAD

**Issue by pllim** [spacetelescope/reftools#24]
Say, @sean-lockwood , would you be interested in this while you're doing the whole acceptance testing stuff with STIS?

**Comment by sean-lockwood** [comment]
I assume `synphot_refactor` uses the same reference files and has the same API?

If so, I could compare the output tables.  Would do this is a couple week after we've updated the instrument TDS in the throughput files.

**Comment by pllim** [comment]
The API here wouldn't change. Yes, `synphot_refactor` should use the same files. Now, I just have to find time to port the code...
