### ISSUE TITLE
Update with new wfc3 reference file tools

### ISSUE THREAD

**Issue by sosey** [spacetelescope/reftools#3]
The wfc3 PCTETAB and IMPHTTAB are different from the ACS tables and require special code. This should be added to this package. Perhaps something to make a sink pixel reference file as well.

**Comment by pllim** [comment]
Huh. I thought at one point, you modified REFTOOLS to support new WFC3 stuff, no?

Also, I thought we are still using Trac for issues, not GitHub... Kind of confusing to have issues in two different systems.

**Comment by pllim** [comment]
@sosey , see your commit 027b22af404b77

**Comment by sosey** [comment]
Yes I know, there's more stuff

Sent from my phone

On Apr 21, 2016, at 2:32 PM, P. L. Lim <notifications@github.com<mailto:notifications@github.com>> wrote:


Huh. I thought at one point, you modified REFTOOLS to support new WFC3 stuff, no?

Also, I thought we are still using Trac for issues, not GitHub... Kind of confusing to have issues in two different systems.

**Comment by pllim** [comment]
Should we create a new ticket on Trac and close this?

**Comment by jhunkeler** [comment]
@plim I'm asking Warren about this now... Just waiting to hear back.

**Comment by sosey** [comment]
No. If we can't commit to svn for this repo and all our work is on git I prefer to make the issue here so I can reference it in my pull request.  Jira is supposed to track the git issues, whenever they hook that up.

**Comment by pllim** [comment]
@jhunkeler , there are 2 l's in my username. Some random guy named Patrick Lim would be so confused at his GitHub notification right now, LoL.

**Comment by jhunkeler** [comment]
Hahaha, I just went with what it autocorrected to!

**Comment by pllim** [comment]
@sosey , I agree *but* that also means we have to move existing Trac tickets here, which is a lot more work.

**Comment by sosey** [comment]
@pllim, I disagree. We don't have to move the trac tickets here, as long as their history and access is kept open to us for reference. But I think it makes sense to start using the git issues for code living here and accepting pull requests so that they can be properly referenced and viewed by everyone.  Not everyone who can see this code can access our trac.  I imagine what will be done is they import the trac issues to Jira and Jira pulls in the git issues, making Jira our primary resource. I believe there are tools already to do this, though I don't know how well they work.

**Comment by pllim** [comment]
As long as the open Trac tickets somehow automagically end up here at some point, that is fine. I just don't want to track tickets in two different systems.

**Comment by pllim** [comment]
It's been 5 years and nothing happened, so I am closing this.
